---
title: "Code Book"
author: "Callum Thomas"
date: "18/05/2020"
output: html_notebook
---

*** 

## The Dataset

The file `new_data.csv` contains the following variables:

- `subject`: The subject ID
- `activity`: The activity undertaken.

Followed by 34 variables taken from the features listed below. The values of these variables in each row represents the average value across multiple replicates for each unique combination of `subject` and `activity`.

The data in this data set were taken from the files present in: *Human Activity Recognition Using Smartphones Dataset
Version 1.0* created by:

Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.  
Smartlab - Non Linear Complex Systems Laboratory  
DITEN - Università degli Studi di Genova.  
Via Opera Pia 11A, I-16145, Genoa, Italy.

***

## Feature Selection

The experiments were carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (*WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING*) wearing a smartphone (Samsung Galaxy S II) on the waist. Using an embedded accelerometer and gyroscope, researchers captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments were video-recorded to label the data manually.

The features selected come from the accelerometer and gyroscope 3-axial raw signals *tAcc-XYZ* and *tGyro-XYZ*. These time domain signals (prefix '*t*' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (*tBodyAcc-XYZ* and *tGravityAcc-XYZ*) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (*tBodyAccJerk-XYZ* and *tBodyGyroJerk-XYZ*). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (*tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag*). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing *fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag*. (Note the '*f*' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.
  
- *tBodyAcc-XYZ*
- *tGravityAcc-XYZ*
- *tBodyAccJerk-XYZ*
- *tBodyGyro-XYZ*
- *tBodyGyroJerk-XYZ*
- *tBodyAccMag*
- *tGravityAccMag*
- *tBodyAccJerkMag*
- *tBodyGyroMag*
- *tBodyGyroJerkMag*
- *fBodyAcc-XYZ*
- *fBodyAccJerk-XYZ*
- *fBodyGyro-XYZ*
- *fBodyAccMag*
- *fBodyAccJerkMag*
- *fBodyGyroMag*
- *fBodyGyroJerkMag*

The set of variables that were estimated from these signals are: 

- *mean()*: Mean value
- *std()*: Standard deviation

***

## Cleaning the Data

The script `run_analysis.R` was used to clean the data present in `new_data.txt`. This script does the following:

1. Imports the raw subject, activity and feature variable data recorded for both *trial* and *test* groups.
2. Concatenates the corresponding *trial* and *test* data together.
3. Labels the feature variable columns with descriptive names taken from the list of features.
4. Renames the activity values with descriptive names taken from the list of activities.
4. Extracts only the *mean()* and *std()* feature variable columns.
5. Combines the subject, activity and feature variable columns together into one dataset.
6. Groups the resulting data by subject and activity and calculates the mean for each grouping.
7. Outputs the new dataset into a file, `new_data.txt`.

***